kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod o+w /drone/src
- name: test
  image: node:12
  user: node
  commands:
  - npm install
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-rest-api-importer
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: secret
name: docker_username
data: oqLPp0OKFpi9uegqDhgxRsnmjqzRUnOLo2wRDoi+ulXQmjp4wB82TuHvAy5G9FkKVXA=
---
kind: secret
name: docker_password
data: gjgehnV1ApbTNtdVwdtIhr1htQACXbA/rf3HDo/seJnlVBxH7RFqk/GjJIXGk2h4YRdq4ehy6ebAdkTXgSWJEDYrMK0PBD6PRnp/TXZl5LtsJwx0bkrOVz12OX8=
