---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:14
    commands:
      - npm audit --package-lock-only --audit-level=high --production

  - name: install
    image: node:14
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: 'true'

  - name: test
    image: node:14
    commands:
      - npm test

  # Not enough coverage
  #- name: check-coverage
  #  image: node:14
  #  commands:
  #    - npm run check-coverage

  - name: build
    image: node:14
    commands:
      - npm run build
      - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-rest-api-importer
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: oqLPp0OKFpi9uegqDhgxRsnmjqzRUnOLo2wRDoi+ulXQmjp4wB82TuHvAy5G9FkKVXA=
---
kind: secret
name: docker_password
data: gjgehnV1ApbTNtdVwdtIhr1htQACXbA/rf3HDo/seJnlVBxH7RFqk/GjJIXGk2h4YRdq4ehy6ebAdkTXgSWJEDYrMK0PBD6PRnp/TXZl5LtsJwx0bkrOVz12OX8=
---
kind: secret
name: ssh_key
data: HlgrfMAl5FD2rTss/KsdEg/NdNzhuQCa7UGmhzP5i+I0aN0OpgW4fq0eIfvEGmafwyahW8sBB5+JZyXJ6GS9eH+OJyeb5HggfAFPbOGms3zcSx0eCOUGJIwYrgqQPCvK958KfpooElXcvtpv7HJfA916lnQABaVNym/N/8FAN2lb1ctLYB5mq9+ZyzRxNaErug1I10g660efEREZbSr6Ldr13JM6sIHmXXvLIGlO1hjXIoqe+/R96M7/JRl+ZyU8xv+u7TUCGTQqNLrdldsVRYXI5RHxKoNH+kgK/qxhI+qYNgci8N39s4L8xEPnUgBfb/5omDT00lmTCs4QZ9jOmqeFfe9zMiYROtIAw20FkGHekZwZQcDJvGJUwbc44jWNEPXqsbXLXrQ6W1memwQ07HHVoWUZyKuWfVLGqpSa7nhVm3M9vddOuwLIlQSr21fwdaxVUmjOYNVrvaG2T0fdcp2nzrYSbR90SrXqz7mI2viMMwGJso3haqvfXujESisRMj7F0lAarb/ClV3qC/tQQvPuu3zv60Z8JQv8FVSU+TeFEuXhGHHUDKtOmq72TL1Fbby0zDW24MbgIANTnKatTfSZ70iBN8SlePtj/aNOFr7wBGg2Rk0kCqXdk1qtqr4fCULIuCUvvhxonBd1qWwImrOzPubPGBRYh8iNOEvo1nQJoxBIwKKX4MgxBXT4AILMRH9+9YSciWfLdlZHyHLVNK27cRfSgEkMYcEDF/99seHOijtNDSmryH+yaJa1qf3L+5zPT+kf48CrrlMfwEDOhRB++CBb6Ki1JKO5v3njKp9lqmX+B2J/dlB8SR0fb8H6InMrzfH7J5JlGUHAQo0XShtByoEpL+/WG4l59+DChce/4WurKKRSYaidmEpmN77fGKzJ+5bSCSNZjL2sORz1cceqf87JpO31edG3u06GEURiSYvqfBjTLCc2QtjDnw/bh3jnLBrf1Oxh5rMpBfrMRhBZcsFkmJkEZNJKUfF4ug8tyAsj2uNZN0GZjIKeKiWzRoeOhc20yUW18PMCGHC19H6DyLuSzgfEvvo7hDwFR3yutjMFPOQngv5dG+4VisysvDo2Y4tEVSYV1muc+nOc2Fnqb24ofppHzJV2rsLCSKr1HhCZ9Dwm9FXz4l2Gn3w+VGedtGN2Ndz6CdgcLO83b2NNka/qv0lfLtkRw8i32bhWy7NBjYgd7m1aXsG3dDjnz9XAn1JR6UlLtCa3ODEt9siYA/NcTSi9dATBOhSxFrUyY7EaF287WFv4KwaLiyb4/mMrNKoE+NtmsB3gKbdvZ1wZJC8iOKGspg+UMs7AWImsyQuQUlM+8A1U6lgzR5K4bjAQJxzZ4Xfe0opw+ZcbruxrurtZ5IfgvJTzAKgVZrSMq5DuWvUqRAYQqnNyFgoW75O6d+EJplnDLD2XrgPmfSxwJqcrtvk6n/xRk4m4FEjuyFcdd2DcrAufEQVZ7FBGAFQKKJX+dKlj96TUNI/5osvwFs2+xMhZLrz4JCRkDf3ILdgp3YVleoER2ekzCG6+7N3flClav3SwQnU2fiMXla/6D63+rCbd7L7lOMT+BbNndZpfkc7V0zl69XPbZg/dULHGBepMR/ThUXXF9Tup1bCSzXIFIOqnsUIC/3NHsD+13QR16KRB6PMwsCW6Nn+OdUqP4KyeBl6xenfKdzWqNpCIHIQBrICdkU+EpxWDRwCVze/AO34bbHI/RmkebphoOB3k6O3lUfrS7NfZt5vzK+LTWpkgA2sJaRaZ63JKUbiqz3Dt9xrGDuFWT2+wIp1rmA4zRh98xhBUCYXC32hceazPlSHOasl62rBu4s/qfxv3fOkRNEjtrv3vqRv4xPeOMPqqTRaLXY6WC4SdcGMvFRB6ob0UnRoKCVpCeBaQOqXUSUrrj2iLRW1sTcLRbyAYLdnOj+G/c597A5eS1BS5M4SuYKztZXCJny5dxLsxbVqBtOgNxCraowJ6M1+xvZKSZ9GAV6jtPTmbfYQiZG7jF28WtQIH3bobsWYka0lTttR4N+RDCMJETC2uJ47v0IQOBbRjbfPGrpam4+QMc/f7Mg9r0ph+9uyA5dVYZmQzcgD/fXAoyC7Ok32+V5AMJ44OanQzMS/Y+6Yqv7T8Ur/+diMe/dpvIVGxAVUBgjT0SwtKZKKA0k9ICBIVEzyWuMH/ciGnoPvHuyRtbfORsKhKG+07rIPN/tyiMg0RPPEN8qWlIpfbroiyHucgmJ3EisB7qdYC3zsT1/6Dkje498iaVlBYL3Yh3xwhFHlwEj5850XAd9unsPAAfBAao54e7KPRFj9G7Z/NGbWlbN0j53pavpT1r+TZ3TfbFXZf0OJtbaFYKo1aVw2t73dTvF7HUEMSvVlwEeG9TPrs4Bimv8HV5pPqkMDkzpPwFnF8p7EEMzEQ/C6DrWLT+aMLxgq8Sq2x+gFvMNc0BOaeac4DAEtSHqBaq5I41hI0P7BIsb8LszIz477MxNTDkrQU2XfV6BqcLrTigeTJ8Jjm7Gy6IepwXnMqXsU2V27dTT3ArsrBeUuG2hNJ+czCR/K7NSycYaC6SlylRPuEe45uNepAcUb59xMUGLJ1/mL65506NlQMOZ4uMfKjetuDulQXqcjU6vTnVNi+YFQxOFKwR2jPx+tTAg9BiwBk02u5CgAS1eDfQA7kNQ7fjCHPJb4M5plxPg1+EV37CYH1yNbMdKOStj9lcNYNaPnYDbq16xflb6R2x7dVORV4wvk8Df1FdMhJ5TZNrDaeah9MyXjdYcSCkv88vHKFlizI9r5dB5yr9VF30CZbnKo7O55Nx1ow6p3VNSveAYDYm7Fpgd1UnIXtLis5jZ3grI5zbYUqY5AM30CN8eKghKxdLtigIfQEg6wsYkNVGWQ9t0Hp8L1XEY3NR5Nrh/fm9CTnhcGtKqbmunn60URAJab9hrrkNaGKsyp7iJhBQCoklhVdhEk6zJbC+OmbbNCEcLOrB1NcZStn5anj7X0XaHR8emqOuUauDmZBbg4KrTMrWuqQFxXdwS0m
---
kind: secret
name: gpg_key
data: q3USwJC6tZtUAaqwbtPVyISBbNv8tnkyBy/HvGykcHSBgoq5vFJ2byE/DmifXCgZKFevSvqApYzF2tCVp5GUiljfTDpOG5nmyA6iqmLbAu11q9fDOyOrEoJbY8lOHRJWV/ImLkCq3Xk9gcaAtoN6xgzliDrM49a/sBOWAYDlYise0H2zLckza2FgxJB9QhiSx1AKMIAND9uIo2limiPhSyc0acfqYrvUcUm8UqvE5JIZpnTeawJ5J0sx92IG0hOMi796/+f8WSllQz6f/t3vTXst+IHwTht4NYrbQaWDNGNTv5a0Mp9aur/dCyABTdSnEcpN7AxvNsxlp2goOBLVH/DTVKAJqy1yfipynjEyry+6Sw3E9iHQ36ds2w1gPH3yADld3Xxb/acHt3CSFjS8Ry7Bmf8KnKOVKt9MRWzDe+gh17X+UXKmr2zyavls5cP/pSjyY+hWRUfZJ74BBraW6toGk5BxB7NMVqSlRm3cTfhVu4qGeDiBRuVfOQQkB7gS6X1vzbEHGeV8pv4FHjeEHl/AtJF1fJNb6SSHadd3PgZNVIgEFBfgZqYgdkS7zowgHz3DzE1ErG6W8ZGH2LQxvRRpUWlIWKOYWjEVRDva8nRx/geB3la75EUhmXY5rUSxe8VdePema7/SRrGNC0oryUwiFpROkcqYW+x+zY8tti3gxcZ9yliCF9qYc4gIwSwrIb6bgEFcaSwUsDz9C4dZdIL/N1Ip/ALzOJQjGr9ggj/efzk61t9sNATji7lyLxgmNpI+OfpZLAxFUkfCb+DdRQYoKrRHN66hpsugkLTFOPnCo7cGR2YeNQNtYZ15np05jr7Byr1XAZVITAwfF9/AAVxPS9QlQNN2bG+KyEMv9tu+1qe9cKEbE1MXbK+NIwnV0fIBiCONWWdexPvpHu/XH2mLVFg9UnRTyNEGW6mVUO8x/ovQBASfQlMvkTyie2ttqgHWleykphvmjw4yrSj0w8CUmA43vgig2XCJR+JEisLxj1Xl1eriGINSRyVRCmEH58WbACy6LP0d2QFnCWz1NmK7RpMBj337rbogpiDftEquBdXZCYAHpIRcWk6ta8I5kzuw3hcd/fDNaphPwkcoCyFuLi4RGV2VJZn106bCxbkxWWHKCvZtxlSseaYBN9RnTtbGNabcT7IftxQzo3i+yhB8+nK6BjZrkwi0RTXUeMq/Xjvn1UETWQe9q01+Ikd0oYbeprquJBgXflQTZmgLNBvmmhFSLScZ6PQ0JGQShEjlSCtyvvGon5uUYi3ZIxk8tXmCh7pg2uu6fNdYdKodloW8hTMSDakZ48T4CB5/4/XvhApyvctLeM0WmmEil+F/oQt0N7Nry0sbyGArLhmYxPVRnk2bHeIFmlGWXcfuOZt/eBPIfsgfnS8sb0BCof2KFkXVz10BwClp4Bl/IqIlt2OEAeQ522ca3fOqWKW+jtjoDdHT0/BLTkYWcHu0WL5hVvzWFOVxMLs2+6QUYn+v6w3VE36GmvMIrytO4GXl1kwN2t93ZxtREkiwsnqAb7N6wDC300pPzkXiHk8pMwo7vrU+nj1xyxIAjToQSYlzu0wY+e2a6kd25CGjPctgCpgMJcJBT5CL2VbpyxFXipnW5HSvii6VMtLasVLjgO7dQjubC/YkUzg1PtDmQWOmrtYhV106lOrlLCPAyCYGPj1ZxOthMfvqO6K+l82VbANdAerNdyNKfa+5d+thV7t2R+tTSXT7lSA308rVRwvyhySiU+SRZHBtTrtJdPZOfOnVaZ/VHtT1Mk9fcYyEEDYjxzMnk83yfaca/w61jdH4OrylZZ/eB2SGVIJ5rUlI6bA0NPc9FwvzM6tRgMAV8ucboHuelSVgU1Lv2Bg4BXjTJJAYWDNBGT4BhxrDh0cwCcNQ9nMlOSwh1mzC9u2NTxHPBmtNHabeLIpylXTTKwED2KkuPsLgtEbyLqB6Qu38Ign5j/HlezjS8pQIVF6DAGT+prIqCG4vgQmtlhqAmLHIiG9dXyxtXnyB/PXmPdPl4kBveOGlrDv5Hamt1uLB0vKURJEURJWHWCsdqLc6Am9GWDEklQINYLfD9D+UhPwPhGvu+MEtlVRj7QxdGa9w7AD9cKujPoiLdiuLmVfqBxe5aLSjydQt1h/qavAsMOOXGI+/TTte1jx+z9htnGNdZzbJp6XxQ4j4huQfi+1ujCucuPXa+3e8xRsqpPqA5CjP+wgBC2owBbnoGhSLQAYAEj8FycZSgiR0jPwt/0JcspbQSYALTXGHN3GqUCXOp5JDDLw3G3RFfC1K8p5UphVXGUMcYNxhWh00Ff1xczUdWHqltS0ceJRETQzdgnanDeYpgaB4X8ToQU8ZumRzKNs3rint8aCtiLArymjn8hZhPxeU55UTTUZpiKFOoV1b5DxC2iEqEDZuXJXYsmopzcaU6E8LQQKbM52ZIYShhY9QMOAlxCZ4xA8m9R5v7yUtU406xJxF+EckqAGak0tYs/YRvs3GTm2TpYyqqZKTMxqRSPLi/AiUVo1w5sPIh0BXDDJp3pzlSMvDcOH01uh4v0eGGPY/sAC2t+7fw07pQ8Vdt6ukM0MzpY4r3B8/CnMpuUASonK9j/UAMJUbO0itSSuhEcb1c6zexnTw+I+fcsOkQ8MxnSutG5bwhlFKYBV8K7PN48QAiRvOi2AyaxUBGBwFKOMHNDoWN5fnDTT2lfVpLdDOyBVho9T5OTlU+/hu4lWUamBXmc17I5WtA3/W9Lq+AVqZ4SAWHUoNGckEBj8zh0tIa8d4hrbb+/mM3lrdP8kgJk13rRkHiOe9CneUqCio5EeLxzGKZNenNjDrn1NeqOn1tYKs2qm+lgcftTl6p1oR0AfwkaPyu3kmVXFcUgBRjQh6M/h9SfYUjvpQcSRwnseNPnqwiNCRfwzs4cEIbD1YQN6e6ryz/IUwxY9mi2fc/JWk0EOf18v6mWvFypPrV1c3Sv9kDuRLFpXvKert5p1QIiUgdAg6GWqHhRLlHVH5EeLhRU7QVAbc5atd+k7NB673iPpGnYiK2otC657DwRzI9V6vr6G8um0cgw5j85U0aNhxI6lmXG+SZ0XH/kS7285ZNpcR6xLKww8oURBWqkDAdPCrlIzl9UmBIXr2vlcFR+w15ZrG1EM81tZDvcLJ7R3HQcN3Ia4wlgXrsX+h15FgAs+lmrQoh1D/sicWIkbqkLPNsS52r3VVgfFkFRQepXTYzCkgAMQynbR1BIHFSFHACdE8NRILrBqRhPTvQ2Fwu+JA2iC16AEFoM1KDtKngY30eyiNAuVUpeRLLEEkhgVXkbk58ISIujC28jbeoYzZrh1POCUNaOqhYYCQ7Act2Wi7lDW/CuiPsDFXiN/OiTbDQimzibM6NGaICuPtMgyK8RV/C3zEUNpclm7hhHSDrqsKVll3qKyedKjGQSjz+8wu9JsGPEryrnXxkq70dk1/bo0l0nYYM9AB38nuwFgWifpsjYuD15ooxbaLzKbjcqFPAqnkn85+GLEyyMG4rgxlH4Q7rZfipf9PeBOUhL+G3I0ioZJ7C3JXXsnwd9JWYLxFhaH3U331iA0VM4fQrukP0aEkBPbt1rqWmFrQDw6Q/+VQtP4TXxRSmetIxQuAoQljZ+ku+qmWSL2a3UAzVhKqZz/CS5KDyKSd5hNljTOaZXqGp/3qOYEpMP+NZ6u5F2PVMlWsUS4OjMEi81ZEXl5208euabYaFnZzZwySk5osWCwzXrCZnKTIfLsPXjdAfWjio+Yh5vKohG32nwvAcFNep3Dguf59KP4iZ6p+4E6IPZRlNEZY0Z+ELaRjTo4A5Jb5WSWjPHNqkZkDE+KF+hRT322i0FMoR/GxJdzJAzLVqzXSoksPvyZDHaQfWS9HY9qPszPmeBaUb1iwQ1KoBzJ4vrukuVJlfoTkQZSByHkKVgJFRJv81cHSbjCqlADyByBqqo8+GGPu1tkJBdyP0224P8z32CoEoPntDdAohPYgEyip9lb4pv7jJ4UW/iUSAYNS+/THb0MziwtuBH9uUpxRvSjwNJa9L0iQEiOu/q54WSvZZFnFqaMp9P1il3XgacS0tQluzIWxwCb1GJcJZVbIuszBfTq0Hg9mP4d40hvgn2Ksi5kw1PGp6DcC9y8Ucbk5o/s+PZP/bfGwZo37IEGLRcxyPzabhzWmUQo2DVU1dRtTCKZHRBAiMlGjukhNJGdpGQFX5bFp8BJs5YDGh8WKDvVR6dFRiU5I0800+VC+6MoDMZASrI9Jg/RwDMykzkZopM+MAc1dKAeCG/pfXZF2So3d18U1tqGqHFR3s+GSfOJYyffg3X5vkqxHujPGpuepwYeSTKSMS4xguPguCZ9wKg9cGELvkmGTSWKbnm3E7lVjuRHoWDYiLtRsYKySRvFnc7ssZBhoW1aSOKGD/kZ33lzYCF9sPLlFcM7EuKBEnUtnbLdelPhsrD1yekJLlMJ9q3aTVYpD0vYwf1bpTfgu3Y7D41v+txhvrRlXef8+C/yeLP4yJYJstjrgbM+1oTiUCr//TnjsDmL3P8biuUAQ3MJd6Kt6a2ZqwlCG61ouFr+gHiSxM7tmDDt/bg02xJ9wK5pJoMJPPdAQQPxZ4vMd6Gqh8vesdoNOeLYooksRwBXJMygBzvKOYOK+KCXS5794YXNvDuW7qUtlD9pxBWheP+Wp1XtyC4lk3uEdOChPhEUqJwNz9xDAJAUN3HwrpNK+tYqp6ldVvnaHgQFp6Uo5KcGXqy/e9FZFn7EZYqbDG3w9oRbm6Olu+j7cxaCBV2MoIpn76ygeJTT/8n6CO22hagUjE8mXqGOwmz1/e0c7B4cWaczI6WvQJZpgmXct2leZgs8jVxymmXMTOt6WSfgJyxEclOv3bJo9XALzAb01rU7ogQeqB09HfShfn/QJl/+pVaJrYhYyFo8KwYczi2Dnwrv59DDClq63wEy1Exlc5rqg2CSPrw3ZebQEoRZVvxCht4gGs9KD30fBez3NrpgeqUdzGtHw+pW6RHOWH0pfsnCJ1T3WzFRY7lDKMAyxHqhI1NKnzWq0nTU0yAC3kR5tpDpQUfdwJmbuZefKPtp1CqcDgKuUNi5RHwb5YRrZoi98oVnfXF/RCpHQKIHCDoiwgyffU2INpmdtFYyvDqY0jskWLy34jA33qmKqamzBBn4ubxVSAXxjhq0yVpoljLFmVva+9wAcNpMuuF9OeKgXJ3TMf86v7erG3Nw5mSpCQa90nKsc8Q7hcm20UJSkD2HsgwWrGoLPHwFFDnaGJbKRsXMmUUTo3UV6F5jCdO8/qIV2ZQy/s+1SMNI470hI8NyERY9fuRCw8N8CLZ8n6BpL9WKIh9Q6cZL4dEvupN0Mbqc8yBqORCu58tBUvR0//fyK7IJlGqYld3cZKnXsksQizyD1t+DOzLihRGtVxDVje14sYo/Mypyw4fHAAn9GEJubRKOEKC1FSlHWRJR3qWTbZ6RAdZEsVzNG8zPVdln//8aRbiY9tFku37TDCTGPWAlPozad/K5yIZUevtZ2ZNV+jRGYRDik2q7R13kgLqR0juc8ECCRZXk0Heja6S48rmyC6E//IEaaDCkxzEkK0XrWzPRWpvO2KsqunUyhcbIIfyJhoM9uzjig/fu8hMIs/2D0PgxDJurBQhRocdhrM3pSym6JbdguVwnYc4ucUfdkA/Y/voxpgm2W8QYTUk8sS8VV4tlkNl/BfBC2+bFlimXpuID8qgsZtMEMe9f7WwBHbr143amXi7Y75pIUjRtIEcXYSQXnoJuO0JZ1C2dSE8xBu4EzIcuGpXFFEm6sGmFoqpYhfe2aTKgAK0jU4R0jShGTmDldRxUvGyf7kapLF/IzQ5+0pzkkhDxS8DQ+PhSse2O/IsZ2QpwF6CjPsLT8THrvRXgjj9hrruIaVr50gB8o1W3MWgtptwarbiUORkAZ9NQL9VN5EphC8otnQSU1qw/h+J/0FJcCwcSTLlfcKm17SjxVcr2/ksVzsImSSw7ESNyGHveOj+9XSmwGDhrbg68VfUAv1bLJm+l2rTkjdKABHCgmvPg8MUMSaI7TFD0Whs1HjPEZtSz7xkadX8PBhL2gAogNRbPTjeynlQMu4Nig9cAfOccLtyHasqa6z2MvUMHpiWqwgebCjD/abTtGeC06PsLCSeZNt5FILG+9wneZo0EV1ejfjwcvvuLApE6dr7Qtjn5Amss236Z/1jRquyNJvYohQ4UfcqmiUmZ28dek+lZJQme1Log+w2heqiTbRjsRpthKzV/RomwkuHgVJWZBx9TGAgFa9f13RT7WADNdgOEHBNXwrWPwGaf2DOJDvqgRL8h2AQSXRviMU7I38JurqC/7gcdeofI6+9we87KlWupxWYveR9WFhEnhaKH+sNfcXk7Es2VvjzEQxv6YykdH9c94/7OMY1XL1ZXYBfduOWiIB83BRV6mok4EkhBpzZ9fjSE6O4DBdEF8jTJj8zw0u72vX6qHJI3ZC123IIXd6nq0ANEFgNdj9eUGIuN0exCRKfN9qjxWWUKzXOrwFwpnkZWN/j8TEK1vHnMO5mb4GV76kX2JlUbV2XO2aAjIpZiSLFNISPeUgFlHr3pwnT7UiwdSeYTWDZwrszoGoIVyC+NTEazY+0RD7q0uYmQQtPUxs8tvJLWPyJqBWMoMTE2HmzDgoEIL6/VJ3f8a+nBQehBmP6tXkS7iVwiKWBu3aoVC7n4fDXmqW593u453bQ==
---
kind: signature
hmac: be15a2b15add9410de058dc84b18045d9c731de480d565250f5b777649150a79

...
